services:
  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ Docker 이미지와 태그
    ports:
      - "5672:5672"  # AMQP 프로토콜 포트
      - "15672:15672"  # RabbitMQ 관리 콘솔 포트
    #volumes:
      #- rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest  # 기본 사용자
      RABBITMQ_DEFAULT_PASS: guest  # 기본 비밀번호

#volumes:
  #rabbitmq_data:
    #driver: local
