### 채팅방 생성
@chatRoomTitle = "새로운 채팅방16"
@createdBy = 49
POST http://localhost:8081/api/chatRoom
Content-Type: application/json

{
  "title": {{chatRoomTitle}},
  "createdBy": {{createdBy}}
}
> {% client.global.set("chatRoomId", JSON.parse(response.body).id); %}

### 특정 채팅방 조회
@chatRoomId = 66a9c29fe5d4af5d2a724efd
GET http://localhost:8081/api/chatRoom/{{chatRoomId}}
Content-Type: application/json


### 유저 ID로 채팅방 목록 조회
GET http://localhost:8081/api/chatRoom/user/{{createdBy}}
Content-Type: application/json

###
GET http://localhost:8081/api/chatRoom/all/chatRoom

### 특정 채팅방 삭제
DELETE http://localhost:8080/api/chatRoom/{{chatRoomId}}
Content-Type: application/json

### 채팅방에 참여자 추가
POST http://localhost:8081/api/chatRoom/participants
Content-Type: application/json

{
  "chatRoomId": "{{chatRoomId}}",
  "userId": 63
}

### 채팅방에서 참여자 제거
DELETE http://localhost:8081/api/chatRoom/participants
Content-Type: application/json

{
  "chatRoomId": "{{chatRoomId}}",
  "userId": 47
}

### 알람 생성
POST http://localhost:8081/api/notification
Content-Type: application/json

{
  "senderId": 61,
  "senderProfile": "",
  "senderName": "허준",
  "receiverId": 57,
  "content": "허허"
}

### 알람 조회
@nofiId = 66a9e1b6b0cdc97af551ca8f
GET http://localhost:8081/api/notification/{{nofiId}}

### 특정 유저의 전체 알람 조회
GET http://localhost:8081/api/notification/user/123

### 알람 읽음 처리
PUT http://localhost:8081/api/notification/read/66a9e1b6b0cdc97af551ca8f



### 메시지 생성
POST http://localhost:8081/api/message
Content-Type: application/json

{
  "chatRoomId": "66aaaa560ce61f457a425630",
  "senderId": 49,
  "senderNickName": "JohnDoe",
  "senderProfileUrl": "http://example.com/profile.jpg",
  "content": "Hello, this is a test message!!!!!",
  "unReadCount": 0
}

### 특정 메시지 조회
@MessageID = 66a9e426b0cdc97af551ca91
GET http://localhost:8081/api/message/{{MessageID}}

### 특정 채팅방의 메시지 리스트 조회
@ChatRoomId = 66a9c29fe5d4af5d2a724efd
GET http://localhost:8081/api/message/chatRoom
Content-Type: application/json

{
  "chatRoomId": "{{ChatRoomId}}",
  "userId": 62
}

### 메시지 삭제
DELETE http://localhost:8081/api/message/60c72b2f4f1a256b9b5d8e2e

### 메시지 수신 처리 (읽음 처리)
PUT http://localhost:8081/api/message/read/60c72b2f4f1a256b9b5d8e2e
