spring:
  data:
    mongodb:
      repositories:
        type: imperative
      uri: mongodb+srv://vosxja1:1q2w3e4r%21%21%40@cluster0.qkkjdrh.mongodb.net/message
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true